{{- if .Values.postgres.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
    {{- include "canette.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
{{- end }}
