apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "canette.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "canette.buildNamespace" . }}
  labels:
    {{- include "canette.labels" . | nindent 4 }}
