version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      fumadocs:
        patterns:
          - "fumadocs-*"
          - "lucide-react"
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories:
      - "/apps/controller"
      - "/apps/builder"
      - "/apps/logstreamer"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
