apiVersion: v1
kind: Service
metadata:
  name: canette-logstreamer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: canette-logstreamer
    {{- include "canette.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: canette-logstreamer
  ports:
    - port: 8080
      targetPort: 8080
