apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: {{ include "canette.buildNamespace" . }}
  labels:
    app.kubernetes.io/name: buildkitd
    {{- include "canette.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkitd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkitd
    spec:
      {{- if .Values.buildkit.rootless }}
      securityContext:
        seccompProfile:
          type: Unconfined
        appArmorProfile:
          type: Unconfined
        fsGroup: 1000
      {{- else }}
      securityContext:
        fsGroup: 1000
      {{- end }}
      containers:
        - name: buildkitd
          image: {{ include "canette.buildkitImage" . }}
          imagePullPolicy: {{ include "canette.imagePullPolicy" (include "canette.buildkitImage" .) }}
          args:
            - --addr
            - tcp://0.0.0.0:1234
            {{- if .Values.buildkit.rootless }}
            - --oci-worker-no-process-sandbox
            {{- end }}
            - --config
            - /etc/buildkit/buildkitd.toml
          ports:
            - containerPort: 1234
          {{- if .Values.buildkit.rootless }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: Unconfined
          {{- else }}
          securityContext:
            privileged: true
          {{- end }}
          volumeMounts:
            - name: buildkit-state
              mountPath: {{ if .Values.buildkit.rootless }}/home/user/.local/share/buildkit{{ else }}/var/lib/buildkit{{ end }}
            - name: buildkitd-config
              mountPath: /etc/buildkit
              readOnly: true
          readinessProbe:
            exec:
              command: ["buildctl", "--addr", "tcp://localhost:1234", "debug", "workers"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.buildkit.resources | nindent 12 }}
      volumes:
        - name: buildkit-state
          emptyDir: {}
        - name: buildkitd-config
          configMap:
            name: buildkitd-config
