apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: {{ include "canette.buildNamespace" . }}
  labels:
    app.kubernetes.io/name: buildkitd
    {{- include "canette.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: buildkitd
  ports:
    - port: 1234
      targetPort: 1234
