apiVersion: v1
kind: ServiceAccount
metadata:
  name: canette-build-job
  namespace: {{ include "canette.buildNamespace" . }}
  labels:
    {{- include "canette.labels" . | nindent 4 }}
  {{- with .Values.builder.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
